### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lukariosmen** [Bunnky/SlimeVision#2]
## Description (Required)
Plugin is not working.

## Steps to reproduce the Issue (Required)
Use paper 1.20.4, and start the server

## Server Log / Error Report
```
[04:01:47] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'SlimeVision.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.2
	at org.bukkit.craftbukkit.v1_20_R3.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:389) ~[paper-1.20.4.jar:git-Paper-496]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:119) ~[paper-1.20.4.jar:git-Paper-496]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.20.4.jar:git-Paper-496]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.20.4.jar:git-Paper-496]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.20.4.jar:git-Paper-496]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[paper-1.20.4.jar:git-Paper-496]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:507) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1131) ~[paper-1.20.4.jar:git-Paper-496]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-496]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
```

 - Minecraft Version: 1.20.4 Paper (496)
 - Slimefun Version: Dev - 1154
 - Plugin Version: Build 2

**Comment by Bunnky** [comment]
This isn't a Slime Vision issue. Runs fine with the provided info:
![image](https://github.com/user-attachments/assets/b39f1960-1101-4779-800e-14f546a36766)

**Comment by Bunnky** [comment]
Looks like i was wrong! Fixed here https://github.com/Bunnky/SlimeVision/commit/ae1d78dcf49a3cb89a39fc87e69e2a32411b5d89
